
version: '3.8'

services:
traefik:
  image: traefik:v2.10
  container_name: traefik
  environment:
    - TZ=Africa/Nairobi
    - TRAEFIK_API=true
    - TRAEFIK_API_INSECURE=false
    - TRAEFIK_API_DASHBOARD=true
    - TRAEFIK_LOG_LEVEL=INFO
    - TRAEFIK_PROVIDERS_DOCKER=true
    - TRAEFIK_PROVIDERS_DOCKER.ENDPOINT=unix:///var/run/docker.sock
    - TRAEFIK_PROVIDERS_DOCKER.EXPOSEDBYDEFAULT=false
    - TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS=:80
    - TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS=:443
    - TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_HTTP_TO_HTTPS=true
  volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - ./data/traefik/acme.json:/acme.json
  labels:
     - "traefik.enable=true"
     - "traefik.http.routers.n8n.entrypoints=https"
     - "traefik.http.routers.n8n.rule=Host(`n8n.leadsflowsys.online`)"
  
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      TZ: Africa/Nairobi
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - automation-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  automation-net:
    driver: bridge
